CREATE Table if NOT EXISTS photo(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  url TEXT NOT NULL UNIQUE,
  locations TEXT NOT NULL,
  encodes TEXT NOT NULL
);
CREATE Table if NOT EXISTS face(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  location TEXT NOT NULL,
  encode TEXT NOT NULL
);

